import '@ant-design/v5-patch-for-react-19';
import type { Metadata } from "next";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { AuthProvider } from '@/lib/auth-provider';
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-CN">
      <body>
        <AntdRegistry>
          <AuthProvider>{children}</AuthProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
